### ISSUE TITLE
Expand test suite

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/pan-learning-djangotools#10]
The test suite should be expanded

**Comment by willend** [comment]
@moving-northwards as the refers to the (Django-based) web-simulator that we are thinking to replace by a docker container that uses the [Jupyter desktop server](https://github.com/yuvipanda/jupyter-desktop-server) I think we could even close this one and not open the other ones.

**Comment by moving-northwards** [comment]
Ok - I will close this issue.
