### ISSUE TITLE
Federated AAI

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/pan-learning-djangotools#11]
I want to be able to login with my Umbrella ID

This issue can be converted to a milestone if beneficial

**Comment by thomasholmrod** [comment]
@kgalal can you give a status update?

**Comment by kgalal** [comment]
Can currently connect to UmbrellaID test server using the ESS Keycloak server. However, there are redirection issues that still need to be resolved. I have received possible solution options that require updating current configuration to Keycloak server to test the solution.

**Comment by kgalal** [comment]
Keycloak server is still showing redirection and Java errors:
```
2021-05-11 13:41:17,409 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-18) Failed to make identity provider oauth callback: java.lang.NullPointerException
```

**Comment by thomasholmrod** [comment]
@AlexandreStefanov what is status?

**Comment by willend** [comment]
@AlexandreStefanov has reported that AAI is now functional, I can confirm this is the case. Closing.
