### ISSUE TITLE
Clarification of the two ways to open Jupyter

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/pan-learning-djangotools#21]
With implementation of the Illumidesk solution there is two ways to open a notebook, one with a big botton that launches JupyterHub and the other is in the menu which can be used to open an Illumidesk notebook. 

It should be made readily clear for a user that there are these two options and the two options should be put on the same footing - or the ordinary way of opening a notebook should be removed if redundant

**Comment by moving-northwards** [comment]
There are now two separate courses based on the IKON python course (one with [Jupyterhub](https://pan-learning.org/moodle/course/view.php?id=36) the other with [Illumidesk](https://pan-learning.org/moodle/course/view.php?id=81)).
Each has its own instructions for how to access the notebooks.

**Comment by thomasholmrod** [comment]
Discussed at meeting dedicated to future of Jupyter in pan-learning. Decided to move ahead with JuPyter Hub solution
