### ISSUE TITLE
Wordpress front page removal

### ISSUE THREAD

**Issue by moving-northwards** [pan-training/pan-learning-djangotools#34]
- [x] Make a copy of all information currently displayed on the front page @moving-northwards 
- [x] Decide what information still needs to be added to moodle @moving-northwards @willend
@thomasholmrod : There some additional logos: KU, DTU and Interreg IVA which are not mentioned currently on moodle - do these need to be added somewhere?
- [x] While there is no AAI/Umbrella ID, add link to signup on moodle login page https://sim.e-neutrons.esss.dk/signup (is this ok?) @willend 
- [x] Remove the word press front page @AlexandreStefanov @kgalal @willend 
Will pan-learning.org/moodle become pan-learning.org or will pan-learning.org just forward to /moodle ?
Will this have any effect on pan-learning.org/wiki ?

- [x] Ensure links to pan-learning.org on panosc.eu still work @moving-northwards 
- [ ] Get expands.eu to also display a link to pan-learnig @moving-northwards

**Comment by willend** [comment]
Good @moving-northwards, this looks like a plan!

Wrt. the the signup-link, I think there may even be a Moodle setting somewhere that allows this, I will investigate.

**Comment by willend** [comment]
@moving-northwards after having looked for a good while, it seems there is a mechanism to replace the full login-page but not the other detail. Do you have ideas how to stitch the link onto the existing login page?

**Comment by moving-northwards** [comment]
Check out the test site login in page. What do you think?

Everything currently written on the word press front page can be found here: https://github.com/pan-training/pan-learning-djangotools/tree/master/landingpage/archivedcontents

**Comment by willend** [comment]
I think the test site login page looks very nice and does the job!

**Comment by moving-northwards** [comment]
Super - I've added it to the production site as well. 
So far the funding information, data policy and link to wiki pages has been added to the moodle frontpage and dashboard.
What I'm not sure about is all the additional logos on the about pan-learning page.
E.g. 7th framework program, nmi3, DTU, Copenhagen university, Interreg IV A etc.

**Comment by willend** [comment]
Perhaps it would be nice to add some sort of "about" page where we can name-drop all of the legacy things, with logos etc.? Let's maybe discuss with Thomas in the near future.

**Comment by AlexandreStefanov** [comment]
Wordpress has been removed and the landing page http://pan-learning.org redirected to https://pan-learning.org/moodle

**Comment by moving-northwards** [comment]
An about page is being added [https://pan-learning.org/moodle/customfiles/about](https://pan-learning.org/moodle/customfiles/about). This will be linked to from the moodle front page. The contents of the page will be discussed in a new issue. 

ExPaNDS has been contacted about adding an obvious link to pan-learning on their website.

**Comment by moving-northwards** [comment]
I have yet to receive a response from ExPaNDS. As everything to do with the wordpress is done, this issue will be closed and a new issue will be opened regarding ExPaNDS having a permanent link to pan-learning.org on their website.
